Convert Searchbar to Typescript
strapi/design-system pull request #1037
Opened 2023-05-11 10:47 UTC by Minecraftschurli

### What does it do?
Converts Searchbar to Typescript

### Related issue(s)/PR(s)
https://github.com/strapi/design-system/issues/983

2023-05-11 12:19 UTC, HichamELBSI approved these changes
Looks good! Thank you 😄

2023-05-11 12:22 UTC, joshuaellis requested changes
Minor tweaks, but looks great!

2023-05-11 12:22 UTC, joshuaellis commented on packages/strapi-design-system/src/Searchbar/Searchbar.tsx
> +    const actualRef = ref || inputRef;
we have a `composeRefs` hook / function that I would use here instead imo 👍🏼

2023-05-11 12:22 UTC, joshuaellis commented on packages/strapi-design-system/src/Searchbar/Searchbar.tsx
> +`;
I think this could probably become `styled(SearchIcon)`?

2023-05-11 12:22 UTC, joshuaellis commented on packages/strapi-design-system/src/Searchbar/Searchbar.tsx
> +`;
This could probably become `styled(CloseIcon)` I think?

2023-05-11 12:22 UTC, joshuaellis commented on packages/strapi-design-system/src/Searchbar/SearchForm.tsx
> +import React from 'react';
```suggestion
import * as React from 'react';
```

2023-05-12 08:28 UTC, joshuaellis commented on packages/strapi-design-system/src/Searchbar/Searchbar.tsx
> +      inputRef?.current?.focus?.();
would `inputRef` ever not have `current` 🤔  also if it's not `null` surely it'll have `focus()` right?

2023-05-12 08:29 UTC, joshuaellis approved these changes
Minor change to discuss but other than that this is really great ⭐

2023-05-12 10:26 UTC, merged