Chore: Convert Pagination (v2) to Typescript
strapi/design-system pull request #1067
Opened 2023-05-19 14:17 UTC by gu-stav

### What does it do?

Converts `v2/Pagination` to Typescript.

### Why is it needed?

https://github.com/strapi/design-system/issues/983

2023-05-22 15:13 UTC, joshuaellis requested changes
Minor tweaks, looks good otherwise 👍🏼

2023-05-22 15:13 UTC, joshuaellis commented on packages/strapi-design-system/src/v2/Pagination/components.tsx
> +  children: React.ReactNode;
```suggestion
```

not sure you need this as `BaseLinkProps` already has children.

2023-05-22 15:13 UTC, joshuaellis commented on packages/strapi-design-system/src/v2/Pagination/components.tsx
> +export const NextLink = React.forwardRef<HTMLElement, PaginationLinkProps>(({ children, ...props }, ref) => {
```suggestion
export const NextLink = React.forwardRef<HTMLAnchorElement, PaginationLinkProps>(({ children, ...props }, ref) => {
```

2023-05-22 15:13 UTC, joshuaellis commented on packages/strapi-design-system/src/v2/Pagination/components.tsx
> +export const PageLink = React.forwardRef<HTMLElement, PaginationPageLinkProps>(
```suggestion
export const PageLink = React.forwardRef<HTMLAnchorElement, PaginationPageLinkProps>(
```

2023-05-23 18:39 UTC, gu-stav commented on packages/strapi-design-system/src/v2/Pagination/components.tsx
> +export const PreviousLink = React.forwardRef<HTMLElement, PaginationLinkProps>(({ children, ...props }, ref) => {
Good idea to make them more specific.

2023-05-24 18:06 UTC, joshuaellis approved these changes
nice work!

2023-05-24 18:06 UTC, merged