fixed:[bug]: Combobox returning NULL if not option is given #1185
strapi/design-system pull request #1186
Opened 2023-07-10 15:39 UTC by noobCode-69

### What does it do?

It fixes the bug [bug]: Combobox returning NULL if no option is available #1185

### Why is it needed?

Bad User experience (UX)

### Related issue(s)/PR(s)
The issue "CM: Relations no longer display "No relations available" when target CT is empty #17231" is related to this.

2023-07-10 15:41 UTC, noobCode-69 commented
Hey @joshuaellis can you please review this!!
This issue is causing the bug "CM: Relations no longer display "No relations available" when target CT is empty #17231" in the main repo

2023-07-11 07:24 UTC, joshuaellis requested changes

2023-07-11 08:25 UTC, noobCode-69 commented on packages/primitives/src/components/Combobox/Combobox.tsx
> +  if (items.length === 0) {
On it @joshuaellis

2023-07-11 08:59 UTC, noobCode-69 commented
Hey @joshuaellis  , I'm not sure about writing test for this. but I can say that there is no such case of regression here. 
- To test the use case though . Go to stories docs -> stories -> combobox.stories.mdx 
- For any of the remove all the ComboboxOption of any component
- Go to localhost:6006 
- You will see that there are no placeholder like 'No option available' 
- But after this PR , there is this placeholder message written

2023-07-11 09:01 UTC, noobCode-69 commented
While rendering options in the 'strapi-design-system/src/Combobox/Combobox.tsx/' in the ComboboxInput component we are returning this
```js
          <Viewport ref={viewportRef}>
            {children}
            {creatable ? (
              <ComboboxPrimitive.CreateItem onPointerUp={handleCreateItemClick} onClick={handleCreateItemClick} asChild>
                <OptionBox>
                  <Typography>{createMessage(internalTextValue ?? '')}</Typography>
                </OptionBox>
              </ComboboxPrimitive.CreateItem>
            ) : null}
            {!creatable && !loading ? (
              <ComboboxPrimitive.NoValueFound asChild>
                <OptionBox $hasHover={false}>
                  <Typography>{noOptionsMessage(internalTextValue ?? '')}</Typography>
                </OptionBox>
              </ComboboxPrimitive.NoValueFound>
            ) : null}
            {loading ? (
              <Flex justifyContent="center" alignItems="center" paddingTop={2} paddingBottom={2}>
                <Loader small>{loadingMessage}</Loader>
              </Flex>
            ) : null}
            <Box id={intersectionId} width="100%" height="1px" />
          </Viewport>

```
You can see that we are rendering
- childrens
- creatables (if any)
- no value found
- loading 
So ideally ComboboxPrimitives.NoValueFound should be handling this condition

2023-07-11 09:44 UTC, noobCode-69 commented on packages/primitives/src/components/Combobox/Combobox.tsx
> +  if (items.length === 0) {
ok! working on it!

2023-07-11 14:04 UTC, closed without merging