Feat: new filter "contains" is added on combobox for autocomplete type:list
strapi/design-system pull request #1605
Opened 2024-02-22 11:56 UTC by madhurisandbhor

### What does it do?

Till now we were filtering by default matching starting character and autocomplete accepted values were: "none", "list", "both". Now we have added a new option `contains` to filter by substring. 

However `filter:'contains'` option is only available on `autocomplete='list'` as having for `autocomplete="both"` would not work as expected. Also to have backward compatibility and for consistency across all supported filter types, we are introducing object counterparts of existing types.

### Why is it needed?
Filtering by substring is required in timezone dropdown in scheduling releases as TZ starts with UTC and not actual TZ value.

### How to test it?

You can test newly added filter option in storybook under `primitives/combobox` as well as `DS/combobox` component

2024-02-22 12:14 UTC, madhurisandbhor commented on docs/stories/Combobox.stories.tsx
> +type TAutocomplete = 'none' | 'list' | 'both' | { type: 'list'; filter: 'startsWith' | 'contains' };
could not import ComboboxProps here to fetch type of autocomplete 😕

2024-02-23 11:38 UTC, joshuaellis reviewed
I was meant to send this yesterday but I didn't post it!

2024-02-26 08:28 UTC, joshuaellis requested changes
Really great work, super clear and concise, good documentation updates too. Lets add some tests for the filtering updates and it's probably good to go! ⭐

2024-02-26 17:44 UTC, joshuaellis approved these changes

2024-02-27 04:57 UTC, merged