Feature: margin and padding logical props
strapi/design-system pull request #1685
Opened 2024-04-15 05:58 UTC by madhurisandbhor

### What does it do?

Mapping `margin` and `padding` internally to equivalent logical props.

### Why is it needed?

To support [direction](https://developer.mozilla.org/en-US/docs/Web/CSS/direction) and [writing modes](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) in DS

### How to test it?

You can check logical properties story added for demo purpose(to be improved/updated in RTL feat) where on inspect you can see all margin and padding properties are converted to equivalent logical properties.

2024-04-16 10:55 UTC, madhurisandbhor commented on packages/strapi-design-system/src/Box/Box.tsx
I don't think so, even if you do not use direction/writing mode, its going to be default prop (like paddingTop).

2024-04-16 17:53 UTC, joshuaellis requested changes
I think lets take this opportunity to make better typography docs since we should be able to support RTL text.

What do you think of Nasa's typography folder? https://nasa-jpl.github.io/explorer-1/?path=/docs/foundation-typography--fonts Interested to hear if you've found any that you really like :)

2024-04-17 10:22 UTC, madhurisandbhor commented
@joshuaellis I did check few design systems for typography folder and I agree we should definitely improve ours. Adobe spectrum also looks good, but Nasa's more simpler like we have with storybooks.
But why don't we do it as a separate PR or with RTL?

2024-04-17 11:00 UTC, madhurisandbhor commented
https://canvas.workday.com/tokens/type is interesting too

2024-04-18 10:22 UTC, joshuaellis approved these changes

2024-04-18 10:25 UTC, merged