Guide/contributing
strapi/design-system pull request #477
Opened 2021-12-28 15:42 UTC by HichamELBSI

2021-12-28 16:21 UTC, ronronscelestes approved these changes
LGTM 🚀

2021-12-29 08:26 UTC, soupette requested changes

2021-12-29 08:26 UTC, soupette commented on CONTRIBUTING.md
> +All efforts to contribute are highly appreciated, we recommend you talk to a maintainer prior to spending a lot of time making a pull request that may not align with the project roadmap.
> we recommend you talk to a maintainer prior to spending a lot of time making a pull request that may not align with the project roadmap.

Maybe we could add "by opening an issue..."

2021-12-29 08:26 UTC, soupette commented on CONTRIBUTING.md
> +We are using [GitHub Issues](https://github.com/strapi/design-system/issues) to manage our public bugs. We keep a close eye on this so before filing a new issue, try to make sure the problem does not
In the codesandbox do we need to import the styles.css?

2021-12-29 08:26 UTC, soupette commented on CONTRIBUTING.md
> +```bash
This command is the same as in step 4 is it wanted?

2021-12-29 08:26 UTC, soupette commented on package.json
> +    "test:watch": "yarn --cwd packages/strapi-design-system test:watch",
We should use lerna with the `--scope` flag instead.

Here's the [documentation](https://www.npmjs.com/package/@lerna/filter-options)

2021-12-29 13:54 UTC, soupette approved these changes
LGTM! Good job

2021-12-29 15:21 UTC, merged