FieldInput: Make input element cover the whole box
strapi/design-system pull request #579
Opened 2022-03-16 13:22 UTC by gu-stav

Before this PR the actual `input` element didn't cover the full height of it's wrapper. This leads to the problem that you can not click everywhere since the click might end up in the wrapper.

This PR removes height from the wrapper and bumps to a height of the input elements to the same as the container by using padding. It is not possible to use `height` on input fields - therefore I had to use some magic numbers.

| Before  | After  |
|---|---|
| <img width="1172" alt="Screenshot 2022-03-16 at 14 18 00" src="https://user-images.githubusercontent.com/2244375/158598694-341a117a-95ce-4d46-bd57-8d66d877deed.png">  | <img width="1172" alt="Screenshot 2022-03-16 at 14 18 13" src="https://user-images.githubusercontent.com/2244375/158598689-0b8f37e4-e337-4168-a1f7-3647619fa7a0.png">  |

2022-03-16 13:27 UTC, HichamELBSI approved these changes
LGTM thanks.

2022-03-16 14:53 UTC, ronronscelestes requested changes
hey, on my way to check more precisely how we can handle it but not using getThemeSize also means that we lose the S size documented in the DS system 😰

2022-03-16 15:08 UTC, gu-stav commented
@ronronscelestes Ah, I didn't see how/ if the small size would be affected by that. If so (I'll double-check tomorrow), we could just reduce the padding for that size I guess. Or do you have something different in mind?

2022-03-17 09:20 UTC, gu-stav commented
@ronronscelestes I've fixed `size=S` - thanks again. Very good catch!

For now, I'd keep the padding definition local, because I don't think we should advertise it since all other components use an explicit height. It works for them because they aren't native input fields.

I'd consider this a fix and not a methodology. If we would put it into a general schema/ function, we'd need to find a good name for it and start to advertise its usage. I'd therefore keep it local to the component if it's ok for you.

2022-03-17 11:14 UTC, ronronscelestes commented
hey @gu-stav 
thanks for the fix!

tbh I'm not 100% fan we remove usage of sizes object for the inputs, that would be nice indeed to find a more global way to handle this.
maybe we could at least add a card in the DS backlog to make sure we don't forget it? WDYT @HichamELBSI?

2022-03-28 15:58 UTC, HichamELBSI commented
Can we merge this one @gu-stav ?

2022-03-28 16:04 UTC, gu-stav commented
@HichamELBSI from my side: yes. @ronronscelestes was not happy with the implementation and asked for your feedback. That's the reason why I kept it open.

2022-03-28 16:31 UTC, HichamELBSI commented
Let's merge this PR and create a card in the DS backlog to not forget how we can handle this globally.

2022-03-28 16:31 UTC, merged