Typography: Add documentation about the ellipsis prop
strapi/design-system pull request #610
Opened 2022-05-13 11:32 UTC by gu-stav

### What does it do?

This PR adds documentation for the already existing `ellipsis` prop. Took me some time to figure it out, so I thought it might be helpful for others.

### Why is it needed?

To have a complete documentation about what the `Typography` component is capable of.

2022-05-13 13:46 UTC, HichamELBSI requested changes

2022-05-13 13:46 UTC, HichamELBSI commented on packages/strapi-design-system/src/Typography/Typography.stories.mdx
> +      <Typography ellipsis>Loong text, that will be cut off</Typography>
Can you also add the Props table with `ArgTable` at the end of the mdx file please

2022-05-20 11:31 UTC, HichamELBSI approved these changes

2022-05-20 11:31 UTC, merged

2022-05-20 11:33 UTC, gu-stav commented
@HichamELBSI Apologies - I forgot about this PR 🌻 . Thanks for merging!