[NumberInput]: use useControllableState to handle number vs string inputs.
strapi/design-system pull request #773
Opened 2022-11-16 17:24 UTC by joshuaellis

### What does it do?

* uses useControllableState hook to manage the need to have a state be managed externally but also own it's own internal state

### Why is it needed?

* Mainly because if the component updates for an external source the internal state won't reflect this (e.g. dynamic zone component move)

### Related issue(s)/PR(s)

* closes #658 
* closes #768

2022-11-17 14:27 UTC, udimberto approved these changes
#### 😅 Looks complex to me 

But if it works, it works. 

![](https://media1.giphy.com/media/3oKIPwoeGErMmaI43S/giphy.gif?cid=ecf05e47u41mf7c451o6rwryuv939ulwj5v27rkwa8hlw4bq&rid=giphy.gif&ct=g)

2022-11-17 14:27 UTC, udimberto commented on tools/excludedFolders.js
> +    : ["helpers", ".DS_Store", "v2", "hooks"];
Not blocking, just a suggestion to be more easier to read:
```suggestion
  process.env.IS_V2 === "true"
    ? [".DS_Store", "helpers", "hooks"]
    : [".DS_Store", "helpers", "hooks", "v2"];
```

2022-11-21 10:38 UTC, ronronscelestes requested changes
didn't fully understand the code yet but controlled state ❤️
mainly tested the components so far, found 2 strange behaviours:

decimals break when updating it with keyboard or arrows (plus or minus)

https://user-images.githubusercontent.com/71838159/203029644-80b965b1-0ae0-40f9-b6c0-1455a3ced370.mov



huge numbers give infinity when using minus with keyboard or arrows 
(tested on main to compare, seems it was broken there too since I couldn't update the value at all)

https://user-images.githubusercontent.com/71838159/203029463-496aba1f-4623-43f3-aef3-bf87d44caf71.mov

2022-11-21 10:59 UTC, joshuaellis commented
> decimals break when updating it with keyboard or arrows (plus or minus)

@ronronscelestes do you mean you're expecting the comma to stay instead of changing to a full stop?

2022-11-21 11:03 UTC, ronronscelestes commented
> @ronronscelestes do you mean you're expecting the comma to stay instead of changing to a full stop?

yes I would expect `1,1 -> 2,1 -> 3,1 -> 4,1` - etc, as it does in main branch 👀

2022-11-21 11:08 UTC, joshuaellis commented
> yes I would expect 1,1 -> 2,1 -> 3,1 -> 4,1 - etc, as it does in main branch 👀

you forget i'm British and i do `1.1 -> 2.1` 😭

2022-11-21 11:13 UTC, joshuaellis commented
> huge numbers give infinity when using minus with keyboard or arrows

Think this can be considered an enhancement to the input because we'd need to use something like `BigInt` as those numbers are too large for JS 🥲

2022-11-21 11:39 UTC, ronronscelestes commented
> Think this can be considered an enhancement to the input because we'd need to use something like `BigInt` as those numbers are too large for JS 🥲

true! I still wonder if having it as fixed number (in the video recording from `main` you can see that I cannot update the number with keyboard/arrows) is not better than the infinite bug, wdyt?
I'm not sure how it was done in the code though 🤔

2022-11-21 12:10 UTC, joshuaellis commented
IMO, it should be "broken", because at least then it's not changing the value. I also can't seem to get Infinity on either this branch or `main`. I think we should open a new issue to discuss handling of `BigInt`? Would that work for you? 😄

2022-11-21 14:42 UTC, ronronscelestes commented
> IMO, it should be "broken", because at least then it's not changing the value. I also can't seem to get Infinity on either this branch or `main`. I think we should open a new issue to discuss handling of `BigInt`? Would that work for you? 😄

works for me 😊

2022-11-21 14:43 UTC, ronronscelestes approved these changes
LGTM 💃

2022-11-21 16:04 UTC, joshuaellis commented
Opened #783 @ronronscelestes

2022-11-21 16:04 UTC, merged