[enh] Update Avatar size
strapi/design-system pull request #847
Opened 2023-01-18 17:20 UTC by ronronscelestes

## What

fixes #844
As discussed, Avatar size will now be `32px` / `theme.spaces[7]`

2023-01-18 17:23 UTC, HichamELBSI requested changes
Hi team, 
fyi @maevalienard @ronronscelestes We are using this component in the Cloud header. Updating the size will directly impact the Cloud dashboard.

2023-01-19 08:56 UTC, maevalienard commented
@HichamELBSI In the designs, the avatar is planned for a size of 32*32px in the Cloud dashboard, so unless technical issues, on the UI part it shouldn't be a problem :)

2023-01-19 08:56 UTC, maevalienard approved these changes

2023-01-19 09:45 UTC, HichamELBSI commented
> @HichamELBSI In the designs, the avatar is planned for a size of 32*32px in the Cloud dashboard, so unless technical issues, on the UI part it shouldn't be a problem :)

Great! Thank you for checking.

2023-01-19 09:56 UTC, HichamELBSI approved these changes

2023-01-20 08:22 UTC, joshuaellis approved these changes

2023-01-20 08:30 UTC, merged