[chore] Box position
strapi/design-system pull request #852
Opened 2023-01-23 08:35 UTC by ronronscelestes

## What

Box `position` props was defined but not documented and often not used when it could have been
- documented with proptypes
- used as prop instead of custom style in numerous components
- larger cleanup by using `Box` props instead of custom

2023-01-23 12:05 UTC, joshuaellis requested changes

2023-01-23 12:05 UTC, joshuaellis commented on packages/strapi-design-system/src/Avatar/Avatar.js
> +            width={`${avatarSize / 16}px`}
That's very small! Did you mean rem?

2023-01-24 14:36 UTC, ronronscelestes commented on packages/strapi-design-system/src/Avatar/Avatar.js
> +            width={`${avatarSize / 16}px`}
thanks for catching it 😬

2023-01-24 16:51 UTC, joshuaellis approved these changes

2023-01-24 16:52 UTC, merged